# Generated by Django 4.0.4 on 2022-08-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('testimonial', models.TextField()),
                ('picture', models.ImageField(upload_to='testimonials/')),
                ('rating', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='emp',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='empId',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='working',
        ),
        migrations.AddField(
            model_name='emp',
            name='emp_id',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emp',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
